learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views
from django.contrib.auth import views as auth_views


app_name = 'basic_app'

urlpatterns = [
    path("other/", views.other, name = "other"),
    path("relative_url_templates/", views.relative_url_templates, name = "relative_url_templates"),
    path("list_post", views.ListPost.as_view(), name = "list_post"),
    # <int:pk> will fetch the post with the primary key 
    path("post_detail/<int:pk>", views.DetailPost.as_view(), name = "post_detail"),
    path('add_post/', views.AddPost.as_view(), name='add_post'),
    path('update/<int:pk>', views.UpdatePost.as_view(), name='update_post'),
    path('delete_post/<int:pk>', views.DeletePost.as_view(), name='delete_post'),
    path('register/', views.register, name='register'),
    path('login_page/', auth_views.LoginView.as_view(template_name= 'basic_app/login.html'), name='login'),
    path('logout_page/', auth_views.LogoutView.as_view(template_name= 'basic_app/logout.html'), name='logout'),
    path('edit_form_page/', views.edit_form, name='edit_form'),
    path('pass_form_page/', views.pass_form, name='pass_form'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
    # this is the path to the home page 
    path("", views.index, name = "home"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_templates/basic_app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete =models.CASCADE)
    age = models.IntegerField()
    website = models.URLField(null= True, blank = True)
    def __str__(self):
        return self.user.username

# Create the post category model 
class Category(models.Model):
    cat_name = models.CharField(verbose_name='Category Name', max_length=100)
    description = models.TextField(verbose_name='Description', blank=True, null=True)
    def __str__(self):
        return self.cat_name

# Create the post model 
class Post(models.Model):
    post_title = models.CharField(max_length = 150, verbose_name ='Post Title')
    category = models.ForeignKey(Category, on_delete =models.CASCADE, verbose_name = 'Post Category')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name= 'Author')
    post_img = models.ImageField(blank=True, null=True, verbose_name= 'Post Image')
    create_date = models.DateTimeField(default=timezone.now)
    contents = models.TextField(blank=True, null=True)
    def __str__(self):
        return self.post_title

learning_templates/basic_app/forms.py
from django import forms
from basic_app.models import Post
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        # __all__ will fetch all the form in the Post model in our models.py 
        fields = "__all__"

class RegForm(UserCreationForm):
    class Meta():
        model = User 
        fields = ('username', 'first_name', 'last_name', 'email')

class EditUserForm(UserChangeForm):
    class Meta():
        model = User 
        fields = ('username', 'first_name', 'last_name', 'email')

learning_templates/basic_app/views.py
from django.shortcuts import render, redirect
# import Post model from models 
from basic_app.models import Post
# import PostForm class created in forms.py 
from basic_app.forms import PostForm
# import ListView and DetailView  from django.views.generic 
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView
from basic_app.forms import PostForm, RegForm, EditUserForm
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

# Create your views here.
@login_required
def index(request):
    post = Post.objects.all()
    return render(request, 'basic_app/index.html', {"post": post})
def relative_url_templates(request):
    return render(request, 'basic_app/relative_url_templates.html')
def other(request):
    if request.method == "POST":
        postform = PostForm(request.POST, request.FILES)
        if postform.is_valid():
            postform.save(commit=True)
            return redirect("home")
    else:
        postform = PostForm()
    return render(request, 'basic_app/other.html', {"postform": postform})

# the ListPost view will list out all the post 
class ListPost(ListView):
    model = Post
    template_name = 'basic_app/list_post.html'
    context_object_name = 'post_list'

# the DetailPost view will display the post based on the id of the post 
class DetailPost(DetailView):
    model = Post
    template_name = 'basic_app/detail_post.html'
    context_object_name = 'post_detail'

# the AddPost view will add to the Post model 
class AddPost(SuccessMessageMixin, CreateView):
    model = Post
    template_name = 'basic_app/cbv_form.html'
    form_class = PostForm
    success_url = reverse_lazy('basic_app:add_post')
    success_message = 'Updated successfully'

# the UpdatePost view will update the Post model 
class UpdatePost(SuccessMessageMixin, UpdateView):
    model = Post
    template_name = 'basic_app/cbv_form.html'
    form_class = PostForm
    success_url = reverse_lazy('basic_app:list_post')
    success_message = 'Updated successfully'

# the DeletePost view will delete the Post model 
class DeletePost(DeleteView):
    model = Post
    template_name = 'basic_app/confirm_delete.html'
    success_url = reverse_lazy('basic_app:list_post')

def register(request):
    if request.method == "POST":
        regform = RegForm(request.POST)
        if regform.is_valid():
            regform.save(commit=True)
            return redirect("home")
    else:
        regform = RegForm()
    return render(request, 'basic_app/register.html', {"regform": regform})

def edit_form(request):
    if request.method == 'POST':
        edit_form = EditUserForm(request.POST, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            messages.success(request, 'User edited successfully')
    else:
        edit_form = EditUserForm(instance=request.user)
    return render(request, 'basic_app/edit_form.html', {"edit_key": edit_form})

def pass_form(request):
    if request.method == 'POST':
        pass_form = PasswordChangeForm(data=request.POST, user=request.user)
        if pass_form.is_valid():
            pass_form.save()
            update_session_auth_hash(request, pass_form.user)
            messages.success(request, 'Password changed successfully')
    else:
        pass_form = PasswordChangeForm(user=request.user)
    return render(request, 'basic_app/pass_form.html', {"pass_key": pass_form})

learning_templates/templates/basic_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'basic_app/style.css' %}">
</head>
<body>
    <a href="{% url 'home' %}">Home</a>
    <a href="{% url 'basic_app:relative_url_templates' %}">Relative</a>
    <a href="{% url 'basic_app:add_post' %}">Add Post</a>
    <a href="{% url 'basic_app:other' %}">Other</a>
    <a href="{% url 'basic_app:list_post' %}">List Post</a>
    <a href="{% url 'basic_app:register' %}">Register</a>
    <!-- if user is logged in  -->
    {% if user.is_authenticated %}
        <a href="{% url 'basic_app:logout' %}">Logout</a>
        {% else %}
        <a href="{% url 'basic_app:login' %}">Login</a>
    {% endif %}
    <a href="{% url 'basic_app:edit_form' %}">Edit User</a>
    <a href="{% url 'basic_app:pass_form' %}">Edit Password</a>
    {% block content %}
    {% endblock %}
</body>
</html>

learning_templates/templates/basic_app/cbv_form.html
{% extends 'basic_app/base.html' %}

{% block title %}
List Post
{% endblock %}

{% block content %}
    <h1>
        <!-- if is opened here -->
        {% if not form.instance.pk %}
        Add Post
        {% else %}
        Edit Post
        {% endif %}
        <!-- if ends here  -->
    </h1>
    <!-- if block opened here  -->
    {% if messages %}
    <!-- for block starts here  -->
    {% for message in messages %}
    <div>{{ message }}</div>
    {% endfor %}
    <!-- for block ends here  -->
    {% endif %}
    <!-- if block ends here  -->

    <form method="post" enctype="multipart/form-data">
        <table>
            {{form.as_table}}
            {% csrf_token %}
        </table>
        {% if not form.instance.pk %}
        <button type="submit">Add Post</button>
        {% else %}
        <button type="submit">Edit Post</button>
        {% endif %}
    </form>
{% endblock %}

learning_templates/templates/basic_app/confirm_delete.html
{% extends 'basic_app/base.html' %}

{% block title %}
List Post
{% endblock %}

{% block content %}
<form method="post">
{% csrf_token %}
<input type="submit" value="Delete">
<a href="{% url 'basic_app:list_post' %}">Cancel</a>
</form>
{% endblock %}

learning_templates/templates/basic_app/detail_post.html
{% extends 'basic_app/base.html' %}
{% if post_detail %}
{% block title %}
{{post_detail.post_title}}
{% endblock %}
{% endif %}

{% block content %}
{% if post_detail %}
<p>{{post_detail.post_title}}</p>
<!-- <p>{{p.id}}</p> -->
<img src="{{ post_detail.post_img.url }}" alt="image">
    <p>{{ post_detail.contents }}</p>
    <h5>{{ post_detail.author }}</h5>
    <p>{{ post_detail.create_date }}</p>

{% endif %}
{% endblock %}

learning_templates/templates/basic_app/edit_form.html
{% extends 'basic_app/base.html' %}

{% block title %}
Edit User
{% endblock %}

{% block content %}
<h1>Edit Profile</h1>

<!-- the token that carries our form data  -->
<form action="" method="post">
{{edit_key.as_p}}
{% csrf_token %}
<button type="submit">Submit</button>
</form>
{% endblock %}

learning_templates/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}

{% block title %}
Home
{% endblock %}
<!-- main content starts here  -->
{% block content %}
<h1>This is the home page</h1>
<!-- create an if block  -->
{% if post %}
<!-- create a for loop block  -->
{% for p in post %}
<div>
    <p>{{p.post_title}}</p>
    <img src="{{ p.post_img.url }}" alt="image">
    <p>{{ p.contents }}</p>
    <h5>{{ p.author }}</h5>
    <p>{{ p.create_date }}</p>
</div>
{% endfor %}
<!-- the for loop ends here  -->
{% endif %}
<!-- the if block ends here  -->
{% endblock %}
<!-- main content ends here  -->

learning_templates/templates/basic_app/list_post.html
{% extends 'basic_app/base.html' %}

{% block title %}
List Post
{% endblock %}

{% block content %}
{% if post_list %}
{% for p in post_list %}
<p>{{p.post_title}}</p>
<!-- <p>{{p.id}}</p> -->
<img src="{{ p.post_img.url }}" alt="image">
    <p>{{ p.contents }}</p>
    <h5>{{ p.author }}</h5>
    <p>{{ p.create_date }}</p>
<p><a href="{% url 'basic_app:post_detail' p.id %}">Read more..</a></p>
<p><a href="{% url 'basic_app:update_post' p.id %}">Edit Post</a></p>
<p><a href="{% url 'basic_app:delete_post' p.id %}">Delete Post</a></p>
{% endfor %}
{% endif %}
{% endblock %}

learning_templates/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}

{% block title %}
Login
{% endblock %}

{% block content %}
<h1>Registration page</h1>
<!-- the token that carries our form data  -->
<form action="" method="post" >
{{form.as_p}}
{% csrf_token %}
<button type="submit">Submit</button>
<a href="{% url 'basic_app:register' %}">Register</a>
</form>
{% endblock %}

learning_templates/templates/basic_app/logout.html
{% extends 'basic_app/base.html' %}

{% block title %}
Logout
{% endblock %}

{% block content %}
<h1>Do you really want to logout?</h1>

<a href="{% url 'basic_app:login' %}">Login</a>
</form>
{% endblock %}

learning_templates/templates/basic_app/other.html
{% extends 'basic_app/base.html' %}

{% block title %}
Other
{% endblock %}

{% block content %}
<h1>Other page</h1>
<!-- the token that carries our form data  -->
<form action="" method="post" enctype="multipart/form-data">
{{postform.as_p}}
{% csrf_token %}
<button type="submit">Submit</button>
</form>
{% endblock %}

learning_templates/templates/basic_app/pass_form.html
{% extends 'basic_app/base.html' %}

{% block title %}
Edit Password
{% endblock %}

{% block content %}
<h1>Edit Password</h1>
<!-- the token that carries our form data  -->
<form action="" method="post">
{{pass_key.as_p}}
{% csrf_token %}
<button type="submit">Edit Password</button>
</form>
{% endblock %}

learning_templates/templates/basic_app/register.html
{% extends 'basic_app/base.html' %}

{% block title %}
Register
{% endblock %}

{% block content %}
<h1>Registration page</h1>
<!-- the token that carries our form data  -->
<form action="" method="post" >
{{regform.as_p}}
{% csrf_token %}
<button type="submit">Submit</button>
</form>
{% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
{% extends 'basic_app/base.html' %}

{% block title %}
Relative Url Template
{% endblock %}

{% block content %}
<h1>This is the relative page</h1>
{% endblock %}